### ISSUE TITLE
77. issues.

### ISSUE THREAD

**Issue by ABoyCDog** [cvSoldier/leetcoooooode#1]
function backtrack(n, k ,res, pr, temp) {
    // 剪枝: temp的长度 + [pr, n]的长度 < k,  就不可能构造k长度的temp
    if(temp.length + (n - pr + 1) < k) {
        return
    }
    if(temp.length === k) {
        res.push([...temp]) // temp.slice()
        return
    }
    // 考虑选择当前位置
    backtrack(n, k, res, pr+1, [...temp, pr])
    // 不选择当前位置
    backtrack(n, k, res, pr+1, temp)
}

**Comment by cvSoldier** [comment]
:thumbsup:看不懂 关了

**Comment by ABoyCDog** [comment]
nb嗷
